### ISSUE TITLE
How to do it works?

### ISSUE THREAD

**Issue by natanfelles** [guiguan/autocomplete-javascript#1]
I installed this package by apm but this does nothing. 

If it works, please add a How To.

**Comment by Andronachi-Marian** [comment]
Need to download the doc ?
And how i put if need ?

Ty.

**Comment by ocoka** [comment]
Mm... why you guys just don't look into the code,  when you could see that it's just an atom autogenerated stub, there is no code )))

**Comment by natanfelles** [comment]
Thanks for the answers!
